# Docker Compose pour Facturer
version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: facturer_db
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./server
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./server:/app
    command: npm start

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
    command: npm run dev

volumes:
  db_data:
